In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('processed/playstore.csv')
df2 = pd.read_csv('processed/playstore_reviews.csv')
df3 = pd.read_csv('processed/cities.csv')

In [16]:
df1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64660 entries, 0 to 64659
Data columns (total 13 columns):
App               64660 non-null object
Category          64660 non-null object
Rating            55769 non-null float64
Reviews           64660 non-null int64
Size_in_Bytes     64660 non-null int64
Installs          64660 non-null int64
Type              64650 non-null object
Price             64660 non-null float64
Content Rating    64654 non-null object
Genres            64660 non-null object
Last Updated      64660 non-null object
Current Ver       64602 non-null object
Android Ver       64636 non-null object
dtypes: float64(2), int64(3), object(8)
memory usage: 6.4+ MB

In [19]:
df1.App = df1.App.str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)
df1.Category = df1.Category.str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)
df1.Genres = df1.Genres.str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)
df1["Android Ver"] = df1["Android Ver"].str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)

df1.rename(index=str, columns={"Android Ver": "Android_Ver", "Content Rating": "Content_Rating", "Last Updated":"Last_Updated", "Current Ver":"Current_Ver"}, inplace=True)
#Content Rating    64654 non-null object
#Genres            64660 non-null object
#Last Updated      64660 non-null object
#Current Ver       64602 non-null object
#Android Ver       64636 non-null object

In [22]:
df1.head()

,App,Category,Rating,Reviews,Size_in_Bytes,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000000,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000000,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,U Launcher Lite – FREE Live Cool Themes Hide Apps,ART_AND_DESIGN,4.7,87510,87000000,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000000,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,28000000,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [27]:
df1.Android_Ver.unique()
df1.Current_Ver = df1.Genres.str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)

In [28]:
df1.Last_Updated = df1.Last_Updated.str.replace(',', '/', regex=False).str.replace(' ', '/', regex=False)

In [30]:
df1.Last_Updated = df1.Last_Updated.str.replace('//', '/', regex=False)

In [32]:
df1.head()

,App,Category,Rating,Reviews,Size_in_Bytes,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000000,10000,Free,0.0,Everyone,Art & Design,January/7/2018,Art & Design,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000000,500000,Free,0.0,Everyone,Art & Design;Pretend Play,January/15/2018,Art & Design;Pretend Play,4.0.3 and up
2,U Launcher Lite – FREE Live Cool Themes Hide Apps,ART_AND_DESIGN,4.7,87510,87000000,5000000,Free,0.0,Everyone,Art & Design,August/1/2018,Art & Design,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000000,50000000,Free,0.0,Teen,Art & Design,June/8/2018,Art & Design,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,28000000,100000,Free,0.0,Everyone,Art & Design;Creativity,June/20/2018,Art & Design;Creativity,4.4 and up

In [7]:
df2.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,City
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333,andafiha
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462,parshino
2,10 Best Foods for You,none,Neutral,0.00,0.000000,lumbukokur
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000,tangan
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000,olenesovkhoz

In [11]:
df2.App = df2.App.str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)

In [12]:
df2.Translated_Review = df2.Translated_Review.str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)

array([0.53333333, 0.28846154, 0.        , ..., 0.51145833, 0.7172619 ,
       0.2594697 ])

In [36]:
df3.Region= df3.Region.str.replace('"', '', regex=False).str.replace(',', '', regex=False).str.replace("''", '', regex=False)

In [37]:
df3.head()

,Country,City,AccentCity,Region,Population,Latitude,Longitude
0,cn,yuji,Yuji,1,8278.0,31.935556,116.823056
1,ph,po-oo,Po-oo,H3,27405.0,9.588100,122.472800
2,us,larkdale,Larkdale,IL,7570.0,39.888333,-88.911944
3,de,schonwag,Schönwag,2,16008.0,47.866667,11.050000
4,ao,nova redonda,Nova Redonda,6.0,9164.0,-11.206048,13.843713

In [38]:
df1.to_csv('processed/playstore_2.csv', index=False)
df2.to_csv('processed/playstore_reviews_2.csv', index=False)
df3.to_csv('processed/cities_2.csv', index=False)

In [2]:
df1 = pd.read_csv('processed/playstore_2.csv')
df2 = pd.read_csv('processed/playstore_reviews_2.csv')
df3 = pd.read_csv('processed/cities_2.csv')

In [29]:
df1.Android_Ver.unique()

array(['4.0.3 and up', '4.2 and up', '4.4 and up', '2.3 and up',
       '3.0 and up', '4.1 and up', '4.0 and up', '2.3.3 and up',
       'Varies with device', '2.2 and up', '5.0 and up', '6.0 and up',
       '1.6 and up', '1.5 and up', '2.1 and up', '7.0 and up',
       '5.1 and up', '4.3 and up', '4.0.3 - 7.1.1', '2.0 and up',
       '3.2 and up', '4.4W and up', '7.1 and up', '7.0 - 7.1.1',
       '8.0 and up', '5.0 - 8.0', '3.1 and up', '2.0.1 and up',
       '4.1 - 7.1.1', nan, '5.0 - 6.0', '1.0 and up', '2.2 - 7.1.1',
       '5.0 - 7.1.1'], dtype=object)